// Organization plugin extensions (organization, member, invitation tables)
// Extended with custom fields: timezone, deletedAt
// Generated by Better Auth organization plugin Drizzle adapter.
export {};
