// Better Auth managed tables (users, sessions, accounts, verifications)
// These will be generated by the Better Auth Drizzle adapter during setup.
// See: https://www.better-auth.com/docs/adapters/drizzle
export {};
